# crypto-chart/templates/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  selector:
    app: api # Encontra os Pods do Deployment da API
