# crypto-chart/templates/mongodb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
spec:
  type: {{ .Values.mongodb.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
  selector:
    app: mongodb # Encontra o Pod do StatefulSet com esta label
