services:
    frontend:
       build:
         context: ./frontend
         dockerfile: Dockerfile.frontend
       ports:
         - "8080:80"
       volumes:
         - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    api:
       build:
         context: ./backend
         dockerfile: Dockerfile.api
       depends_on:
         - mongodb   

    mongodb:

      image: mongo:6
      container_name: mongodb
      restart: always
      build:
        context: ./backend/database
        dockerfile: Dockerfile.mongodb
      volumes:
        - mongo-data:/data/db
      expose:
        - "27017"
volumes:
    mongo-data:


networks:
  backendnet:
    driver: bridge











